# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies

      - run:
          name: Build
          command: ./gradlew build
      
      - store_artifacts:
          path: ./build/libs
