# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

executors:
  main-executor:
    docker:
      - image: circleci/openjdk:8-jdk

jobs:
  install:
    executor: main-executor
    
    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout

      - run:
          name: Make gradlew executable
          command: chmod +x gradlew

      - run:
          name: Download Dependencies
          command: ./gradlew dependencies
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - .gradle
            - repo    
            
  build:
    executor: main-executor
    
    working_directory: ~/repo
    
    steps:
      - run:
          name: Build
          command: ./gradlew build
      
      - store_artifacts:
          path: ./build/libs

workflows:
  version: 2.1
  main:
    jobs:
      - install
      - build:
          requires:
            - install
